# Generated by Django 5.0.1 on 2024-04-10 11:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="branchoffice",
            name="establishment",
            field=models.DateField(
                max_length=100, verbose_name="Establishment of the BO"
            ),
        ),
        migrations.AlterField(
            model_name="branchoffice",
            name="facility_id",
            field=models.FloatField(
                max_length=100,
                verbose_name="Facility ID of the BO Profit/Cost centre ID of the BO",
            ),
        ),
    ]
