# Generated by Django 5.0.1 on 2024-04-10 11:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0003_alter_branchoffice_establishment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="branchoffice",
            name="facility_id",
            field=models.IntegerField(
                verbose_name="Facility ID of the BO Profit/Cost centre ID of the BO"
            ),
        ),
    ]
