# Generated by Django 5.0.1 on 2024-04-10 12:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0004_alter_branchoffice_facility_id"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Acquittance",
        ),
        migrations.DeleteModel(
            name="BranchOffice",
        ),
        migrations.DeleteModel(
            name="FinanceAndAccounting",
        ),
        migrations.DeleteModel(
            name="IndiaPostPaymentBank",
        ),
        migrations.DeleteModel(
            name="InspectionReport",
        ),
        migrations.DeleteModel(
            name="LetterBoxes",
        ),
        migrations.DeleteModel(
            name="LookAndFeel",
        ),
        migrations.DeleteModel(
            name="MailOperations",
        ),
        migrations.DeleteModel(
            name="MoneyOrder",
        ),
        migrations.DeleteModel(
            name="MS87",
        ),
        migrations.DeleteModel(
            name="PassbookStatus",
        ),
        migrations.DeleteModel(
            name="PassbookVerification",
        ),
        migrations.DeleteModel(
            name="PassbookVerificationLog",
        ),
        migrations.DeleteModel(
            name="PostalLifeInsurance",
        ),
        migrations.DeleteModel(
            name="ReferenceNumber",
        ),
        migrations.DeleteModel(
            name="SavingsBank",
        ),
        migrations.DeleteModel(
            name="SB26",
        ),
        migrations.DeleteModel(
            name="SB28",
        ),
        migrations.DeleteModel(
            name="Signage",
        ),
        migrations.DeleteModel(
            name="SSAAccount",
        ),
        migrations.DeleteModel(
            name="UnusedReceipts",
        ),
        migrations.DeleteModel(
            name="WorkCarriedOut",
        ),
    ]
