# Generated by Django 5.0.1 on 2024-04-16 19:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0007_inspectionreport_lookandfeel_mailoperations_signage_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailoperations",
            name="date_of_delivery",
            field=models.TextField(verbose_name="Date of delivery"),
        ),
        migrations.AlterField(
            model_name="mailoperations",
            name="date_of_receipt",
            field=models.TextField(verbose_name="Date of receipt"),
        ),
    ]
