# Generated by Django 5.0.1 on 2024-04-17 13:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0008_alter_mailoperations_date_of_delivery_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="InspectionReport",
        ),
        migrations.DeleteModel(
            name="LookAndFeel",
        ),
        migrations.DeleteModel(
            name="Signage",
        ),
        migrations.DeleteModel(
            name="WorkCarriedOut",
        ),
    ]
