# Generated by Django 5.0.1 on 2024-04-17 13:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0009_delete_inspectionreport_delete_lookandfeel_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailoperations",
            name="article_condition",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")], max_length=3
            ),
        ),
        migrations.AlterField(
            model_name="mailoperations",
            name="articles_beyond_period",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")], max_length=3
            ),
        ),
        migrations.AlterField(
            model_name="mailoperations",
            name="check_delivery_status",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")], max_length=3
            ),
        ),
    ]
