# Generated by Django 5.0.1 on 2024-04-17 13:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0011_alter_mailoperations_article_condition_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mailoperations",
            name="article_condition",
        ),
        migrations.RemoveField(
            model_name="mailoperations",
            name="articles_beyond_period",
        ),
        migrations.RemoveField(
            model_name="mailoperations",
            name="check_delivery_status",
        ),
    ]
