# Generated by Django 5.0.1 on 2024-04-17 14:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0013_mailoperations_article_condition_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MailOperations",
        ),
        migrations.AddField(
            model_name="branchoffice",
            name="article_condition",
            field=models.CharField(
                blank=True,
                choices=[("Yes", "Yes"), ("No", "No")],
                default="adn",
                max_length=3,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="branchoffice",
            name="article_condition_comments",
            field=models.TextField(
                default="adn", verbose_name="Comments on article condition"
            ),
        ),
        migrations.AddField(
            model_name="branchoffice",
            name="articles_beyond_period",
            field=models.CharField(
                blank=True,
                choices=[("Yes", "Yes"), ("No", "No")],
                default="adn",
                max_length=3,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="branchoffice",
            name="articles_beyond_period_comments",
            field=models.TextField(
                default="adn",
                verbose_name="Comments on articles beyond prescribed period",
            ),
        ),
        migrations.AddField(
            model_name="branchoffice",
            name="articles_in_deposit_comments",
            field=models.TextField(
                default="adn", verbose_name="No. of articles in deposit"
            ),
        ),
        migrations.AddField(
            model_name="branchoffice",
            name="check_delivery_status",
            field=models.CharField(
                blank=True,
                choices=[("Yes", "Yes"), ("No", "No")],
                default="adn",
                max_length=3,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="branchoffice",
            name="check_delivery_status_comments",
            field=models.TextField(
                default="adn", verbose_name="Comments on delivery status"
            ),
        ),
        migrations.AddField(
            model_name="branchoffice",
            name="compare_articles_comments",
            field=models.TextField(
                default="adn",
                verbose_name="Compare the number of articles in deposit comments",
            ),
        ),
        migrations.AddField(
            model_name="branchoffice",
            name="date_of_delivery",
            field=models.TextField(default="adn", verbose_name="Date of delivery"),
        ),
        migrations.AddField(
            model_name="branchoffice",
            name="date_of_receipt",
            field=models.TextField(default="adn", verbose_name="Date of receipt"),
        ),
    ]
