# Generated by Django 4.1.12 on 2024-04-18 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_delete_mailoperations_branchoffice_article_condition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchoffice',
            name='bo_signage',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default=1, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='branchoffice',
            name='look_and_feel',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default=1, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='branchoffice',
            name='look_and_feel_comments',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='branchoffice',
            name='previous_inspection_comments',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='branchoffice',
            name='previous_inspection_pending',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default=1, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='branchoffice',
            name='signage_comments',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='branchoffice',
            name='work_carried_out',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default=1, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='branchoffice',
            name='work_carried_out_comments',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
