# Generated by Django 4.1.12 on 2024-06-02 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_branchoffice_bo_signage_branchoffice_look_and_feel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchoffice',
            name='check_delivery_status',
            field=models.JSONField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default=dict, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='branchoffice',
            name='check_delivery_status_comments',
            field=models.JSONField(default=dict, verbose_name='Comments on delivery status'),
        ),
        migrations.AlterField(
            model_name='branchoffice',
            name='date_of_delivery',
            field=models.JSONField(default=dict, verbose_name='Date of delivery'),
        ),
        migrations.AlterField(
            model_name='branchoffice',
            name='date_of_receipt',
            field=models.JSONField(default=dict, verbose_name='Date of receipt'),
        ),
    ]
