# Generated by Django 4.1.12 on 2024-06-02 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_alter_branchoffice_check_delivery_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchoffice',
            name='check_delivery_status',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='branchoffice',
            name='check_delivery_status_comments',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Comments on delivery status'),
        ),
        migrations.AlterField(
            model_name='branchoffice',
            name='date_of_delivery',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Date of delivery'),
        ),
        migrations.AlterField(
            model_name='branchoffice',
            name='date_of_receipt',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Date of receipt'),
        ),
    ]
