# Generated by Django 4.1.12 on 2024-06-02 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_alter_branchoffice_check_delivery_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branchoffice',
            old_name='article_condition',
            new_name='article_condition_acc',
        ),
        migrations.RenameField(
            model_name='branchoffice',
            old_name='article_condition_comments',
            new_name='article_condition_comments_acc',
        ),
        migrations.RenameField(
            model_name='branchoffice',
            old_name='articles_beyond_period',
            new_name='article_condition_ord',
        ),
        migrations.RenameField(
            model_name='branchoffice',
            old_name='articles_beyond_period_comments',
            new_name='articles_beyond_period_comments_acc',
        ),
        migrations.RenameField(
            model_name='branchoffice',
            old_name='articles_in_deposit_comments',
            new_name='articles_in_deposit_comments_acc',
        ),
        migrations.RenameField(
            model_name='branchoffice',
            old_name='check_delivery_status',
            new_name='check_delivery_status_acc',
        ),
        migrations.RenameField(
            model_name='branchoffice',
            old_name='check_delivery_status_comments',
            new_name='check_delivery_status_comments_acc',
        ),
        migrations.RenameField(
            model_name='branchoffice',
            old_name='compare_articles_comments',
            new_name='compare_articles_comments_acc',
        ),
        migrations.RenameField(
            model_name='branchoffice',
            old_name='date_of_delivery',
            new_name='date_of_delivery_acc',
        ),
        migrations.RenameField(
            model_name='branchoffice',
            old_name='date_of_receipt',
            new_name='date_of_receipt_acc',
        ),
        migrations.AddField(
            model_name='branchoffice',
            name='article_condition_comments_ord',
            field=models.TextField(default='adn', verbose_name='Comments on article condition'),
        ),
        migrations.AddField(
            model_name='branchoffice',
            name='articles_beyond_period_acc',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='adn', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='branchoffice',
            name='articles_beyond_period_comments_ord',
            field=models.TextField(default='adn', verbose_name='Comments on articles beyond prescribed period'),
        ),
        migrations.AddField(
            model_name='branchoffice',
            name='articles_beyond_period_ord',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='adn', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='branchoffice',
            name='articles_in_deposit_comments_ord',
            field=models.TextField(default='adn', verbose_name='No. of articles in deposit'),
        ),
        migrations.AddField(
            model_name='branchoffice',
            name='check_delivery_status_comments_ord',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Comments on delivery status'),
        ),
        migrations.AddField(
            model_name='branchoffice',
            name='check_delivery_status_ord',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='branchoffice',
            name='compare_articles_comments_ord',
            field=models.TextField(default='adn', verbose_name='Compare the number of articles in deposit comments'),
        ),
        migrations.AddField(
            model_name='branchoffice',
            name='date_of_delivery_ord',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Date of delivery'),
        ),
        migrations.AddField(
            model_name='branchoffice',
            name='date_of_receipt_ord',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Date of receipt'),
        ),
    ]
