# Generated by Django 4.1.12 on 2024-06-02 15:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0018_rename_article_condition_branchoffice_article_condition_acc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchoffice',
            name='cash_balance_comments',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='Comments on cash balance'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='branchoffice',
            name='cash_balance_correct',
            field=models.BooleanField(default=True, verbose_name='Whether cash balance is correct?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='branchoffice',
            name='cash_value',
            field=models.FloatField(default=1, verbose_name='Cash value'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='branchoffice',
            name='details_in_stock_comments',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='Comments on details of cash, stamp, forms in stock'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='branchoffice',
            name='inventory',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Comments on inventory'),
        ),
        migrations.AddField(
            model_name='branchoffice',
            name='invoice_stamp',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Stamp received through CSI and duly acknowledged? Check invoices received and whether inventory updated.'),
        ),
        migrations.AddField(
            model_name='branchoffice',
            name='last_acknowledged_balance',
            field=models.FloatField(default=1, verbose_name='Last acknowledged BO balance by Account Office through BO slip or DTR.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='branchoffice',
            name='last_acknowledged_balance_comments',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='Comments on last acknowledged balance'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='branchoffice',
            name='last_acknowledged_balance_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date of last acknowledged balance'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='branchoffice',
            name='lb_clearance',
            field=models.BooleanField(default=True, verbose_name='Are LBs cleared punctually? Are timings of clearance suitable?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='branchoffice',
            name='lb_clearance_comments',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='Comments on LB clearance'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='branchoffice',
            name='lb_condition',
            field=models.BooleanField(default=True, verbose_name='Whether LBs painted and in good condition?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='branchoffice',
            name='lb_condition_comments',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='Comments on LB condition'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='branchoffice',
            name='no_of_letter_boxes',
            field=models.IntegerField(default=1, verbose_name='Apart from the office letter box, how many letter boxes are attached to the BO?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='branchoffice',
            name='physical_balance',
            field=models.FloatField(default=1, verbose_name='Physical balance'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='branchoffice',
            name='physical_balance_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date of physical balance'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='branchoffice',
            name='stamp_value',
            field=models.FloatField(default=1, verbose_name='Stamp value'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='branchoffice',
            name='wallet_balance',
            field=models.FloatField(default=1, verbose_name='Wallet balance'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='branchoffice',
            name='wallet_balance_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date of wallet balance'),
            preserve_default=False,
        ),
    ]
