# Generated by Django 4.1.12 on 2024-06-02 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0019_branchoffice_cash_balance_comments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchoffice',
            name='cash_balance_correct',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='adn', max_length=3, null=True, verbose_name='Whether cash balance is correct?'),
        ),
        migrations.AlterField(
            model_name='branchoffice',
            name='lb_clearance',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='adn', max_length=3, null=True, verbose_name='Are LBs cleared punctually? Are timings of clearance suitable?'),
        ),
        migrations.AlterField(
            model_name='branchoffice',
            name='lb_condition',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='adn', max_length=3, null=True, verbose_name='Whether LBs painted and in good condition?'),
        ),
    ]
