# Generated by Django 4.1.12 on 2024-06-03 13:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0020_alter_branchoffice_cash_balance_correct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchoffice',
            name='bo_account',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='BO ACCOUNT'),
        ),
        migrations.AddField(
            model_name='branchoffice',
            name='bo_slip',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='BO SLIP'),
        ),
        migrations.AddField(
            model_name='branchoffice',
            name='date_of_account',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Date of BO account'),
        ),
        migrations.AddField(
            model_name='branchoffice',
            name='postage_due',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='adn', max_length=3, null=True, verbose_name='Examine the Postage Due and amount realized towards unpaid articles and record results.'),
        ),
        migrations.AddField(
            model_name='branchoffice',
            name='postage_due_comments',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='Comments on postage due'),
            preserve_default=False,
        ),
    ]
