# Generated by Django 4.1.12 on 2024-06-04 04:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0022_branchoffice_question_9'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchoffice',
            name='VPMO_issued_comments',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Whether VPMO issued immediately?'),
        ),
        migrations.AddField(
            model_name='branchoffice',
            name='VPMO_issued_date',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='VPMO isssued DATE'),
        ),
        migrations.AddField(
            model_name='branchoffice',
            name='article_delivered_date',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Article Delivered DATE'),
        ),
        migrations.AddField(
            model_name='branchoffice',
            name='article_issued_date',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Article Issued DATE'),
        ),
        migrations.AddField(
            model_name='branchoffice',
            name='article_number',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='No. of VP/COD articles delivered (one day in each month since DLI/DLV)'),
        ),
        migrations.AddField(
            model_name='branchoffice',
            name='article_received_date',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Article received DATE'),
        ),
        migrations.AddField(
            model_name='branchoffice',
            name='demurrage_fees_comments',
            field=models.TextField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='adn', max_length=3, null=True, verbose_name='Comments on whether demurrage fees charged and noted in VP receipt (RP- 55)'),
        ),
        migrations.AddField(
            model_name='branchoffice',
            name='eMO_payment_limit',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='adn', max_length=3, null=True, verbose_name='Test check whether the BPM has given the cash to ABPM (MD) for eMO payment beyond the prescribed limit as mentioned in Directorate letter No.24-3/2012-PO dated 01.10. 2018. Educate the BPM on the procedure to be followed if the amount exceeds the prescribed limit.'),
        ),
        migrations.AddField(
            model_name='branchoffice',
            name='eMO_payment_limit_comments',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='Comments on eMO payment limit'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='branchoffice',
            name='list_of_mo_received',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='adn', max_length=3, null=True, verbose_name='Whether List of MO received for payment is pasted in BO journal and those issued to ABPM (MD) is pasted in Postman Book. Check the same for other accountable articles.'),
        ),
        migrations.AddField(
            model_name='branchoffice',
            name='list_of_mo_received_comments',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='Comments on List of MO received for payment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='branchoffice',
            name='number_of_mo_issued',
            field=models.IntegerField(default=1, verbose_name='No of MO issued since last visit'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='branchoffice',
            name='number_of_mo_received',
            field=models.IntegerField(default=1, verbose_name='No. of MOs received for payment and whether paid promptly. Check promptness with atleast 5 payees. (Mention MO and payee details)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='branchoffice',
            name='payee_details1',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='Payee details 1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='branchoffice',
            name='payee_details2',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='Payee details 2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='branchoffice',
            name='payee_details3',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='Payee details 3'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='branchoffice',
            name='payee_details4',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='Payee details 4'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='branchoffice',
            name='payee_details5',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='Payee details 5'),
            preserve_default=False,
        ),
    ]
