# Generated by Django 4.1.12 on 2024-06-04 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0023_branchoffice_vpmo_issued_comments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchoffice',
            name='article_number',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='No. of VP/COD articles delivered (one day in each month since DLI/DLV)(Article No)'),
        ),
    ]
