# Generated by Django 4.1.12 on 2024-06-07 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0024_alter_branchoffice_article_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchoffice',
            name='BO_journals',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default=1, max_length=3, verbose_name='Whether BO journals and Specimen Signature Book of all POSB Schemes maintained and updated with complete KYC'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='branchoffice',
            name='BO_journals_comments',
            field=models.TextField(default=1, verbose_name='Comments on BO journals'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='branchoffice',
            name='account_number_ao',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Account number for annual interest posting'),
        ),
        migrations.AddField(
            model_name='branchoffice',
            name='all_schemes',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='All schemes for annual interest posting'),
        ),
        migrations.AddField(
            model_name='branchoffice',
            name='amount_from_MS87',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Amount (From)_MS87'),
        ),
        migrations.AddField(
            model_name='branchoffice',
            name='amount_from_SB26',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Amount (From)_SB26'),
        ),
        migrations.AddField(
            model_name='branchoffice',
            name='amount_from_SB28',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Amount (From)_SB28'),
        ),
        migrations.AddField(
            model_name='branchoffice',
            name='amount_to_MS87',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Amount (To)_MS87'),
        ),
        migrations.AddField(
            model_name='branchoffice',
            name='amount_to_SB26',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Amount (To)_SB26'),
        ),
        migrations.AddField(
            model_name='branchoffice',
            name='amount_to_SB28',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Amount (To)_SB28'),
        ),
        migrations.AddField(
            model_name='branchoffice',
            name='blank_receipt_MS87',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Blank Receipt_MS87'),
        ),
        migrations.AddField(
            model_name='branchoffice',
            name='blank_receipt_SB26',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Blank Receipt_SB26'),
        ),
        migrations.AddField(
            model_name='branchoffice',
            name='blank_receipt_SB28',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Blank Receipt_SB28'),
        ),
        migrations.AddField(
            model_name='branchoffice',
            name='book_no_MS87',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Book No_MS87'),
        ),
        migrations.AddField(
            model_name='branchoffice',
            name='book_no_SB26',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Book No_SB26'),
        ),
        migrations.AddField(
            model_name='branchoffice',
            name='book_no_SB28',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Book No_SB28'),
        ),
        migrations.AddField(
            model_name='branchoffice',
            name='cheques_received',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default=1, max_length=3, verbose_name='Whether cheques received in BO entered in cheque register and submitted to account office'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='branchoffice',
            name='cheques_received_comments',
            field=models.TextField(default=1, verbose_name='Comments on cheques received'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='branchoffice',
            name='date_from_MS87',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Date (From)_MS87'),
        ),
        migrations.AddField(
            model_name='branchoffice',
            name='date_from_SB26',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Date (From)_SB26'),
        ),
        migrations.AddField(
            model_name='branchoffice',
            name='date_from_SB28',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Date (From)_SB28'),
        ),
        migrations.AddField(
            model_name='branchoffice',
            name='date_to_MS87',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Date (To)_MS87'),
        ),
        migrations.AddField(
            model_name='branchoffice',
            name='date_to_SB26',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Date (To)_SB26'),
        ),
        migrations.AddField(
            model_name='branchoffice',
            name='date_to_SB28',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Date (To)_SB28'),
        ),
        migrations.AddField(
            model_name='branchoffice',
            name='entries_comparison',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default=1, max_length=3, verbose_name='Compare the entries made in SB/RD/TD/SSA journals with the corresponding entries made in BO account book'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='branchoffice',
            name='entries_comparison_comments',
            field=models.TextField(default=1, verbose_name='Comments on entries comparison'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='branchoffice',
            name='number_of_passbooks_deposit',
            field=models.IntegerField(default=1, verbose_name='Number of passbooks in deposit'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='branchoffice',
            name='number_of_passbooks_deposit_comments',
            field=models.TextField(default=1, verbose_name='Comments on number of passbooks in deposit'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='branchoffice',
            name='passbook_collection_register',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default=1, max_length=3, verbose_name='Check that register for collection of passbooks of SB/PPF/SSA is maintained in Branch Post Office'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='branchoffice',
            name='passbook_collection_register_comments',
            field=models.TextField(default=1, verbose_name='Comments on passbook collection register'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='branchoffice',
            name='receipt_no_from_MS87',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Receipt No (From)_MS87'),
        ),
        migrations.AddField(
            model_name='branchoffice',
            name='receipt_no_from_SB26',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Receipt No (From)_SB26'),
        ),
        migrations.AddField(
            model_name='branchoffice',
            name='receipt_no_from_SB28',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Receipt No (From)_SB28'),
        ),
        migrations.AddField(
            model_name='branchoffice',
            name='receipt_no_to_MS87',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Receipt No (To)_MS87'),
        ),
        migrations.AddField(
            model_name='branchoffice',
            name='receipt_no_to_SB26',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Receipt No (To)_SB26'),
        ),
        migrations.AddField(
            model_name='branchoffice',
            name='receipt_no_to_SB28',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Receipt No (To)_SB28'),
        ),
        migrations.AlterField(
            model_name='branchoffice',
            name='article_issued_date',
            field=models.JSONField(default=1, verbose_name='Article Issued DATE'),
            preserve_default=False,
        ),
    ]
