# Generated by Django 4.1.12 on 2024-06-07 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0025_branchoffice_bo_journals_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchoffice',
            name='acquittance_comments',
            field=models.TextField(default=1, verbose_name='acquittance comments'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='branchoffice',
            name='coreference_number_comments',
            field=models.TextField(default=1, verbose_name='reference number comments'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='branchoffice',
            name='unused_receipts_comments',
            field=models.TextField(default=1, verbose_name='unused receipts comments'),
            preserve_default=False,
        ),
    ]
