# Generated by Django 4.1.12 on 2024-06-10 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0027_rename_coreference_number_comments_branchoffice_reference_number_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchoffice',
            name='account_details_1',
            field=models.CharField(default=1, max_length=100, verbose_name='Account Details 1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='branchoffice',
            name='account_details_2',
            field=models.CharField(default=1, max_length=100, verbose_name='Account Details 2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='branchoffice',
            name='account_details_3',
            field=models.CharField(default=1, max_length=100, verbose_name='Account Details 3'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='branchoffice',
            name='account_details_4',
            field=models.CharField(default=1, max_length=100, verbose_name='Account Details 4'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='branchoffice',
            name='account_details_5',
            field=models.CharField(default=1, max_length=100, verbose_name='Account Details 5'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='branchoffice',
            name='discrepancy_comments',
            field=models.TextField(default=1, verbose_name='Discrepancy Comments'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='branchoffice',
            name='passbook_verified',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default=1, max_length=3, verbose_name='Passbook Verified'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='branchoffice',
            name='passbook_verified_comments',
            field=models.TextField(default=1, verbose_name='Passbook Verified Comments'),
            preserve_default=False,
        ),
    ]
